configure_dotfiles: false

homebrew_installed_packages:
  - asciidoctor
  - asciinema
  - autojump
  - awscli
  - cloudfoundry/tap/cf-cli
  - git
  - glances
  - gradle
  - htop
  - httpie
  - jenv
  - jq
  - ncdu
  - nvm
  - rclone
  - restic
  - tldr
  - watch
  - wget
  - wrk
  - yarn
  - zsh
  - zsh-completions
  
 homebrew_cask_apps:
  - 1password
  - insomnia
  - aerial
  - cleanmymac
  - iterm2
  - contexts
  - java
  - alfred
  - jetbrains-toolbox
  - numi
  - appcleaner
  - discord
  - joplin
  - docker
  - tunnelblick
  - postman
  - logitech-camera-settings
  - firefox
  - skype
  - slack
  - zoom
  - sourcetree
  - spotify
  - google-chrome
  - microsoft-office
  - microsoft-teams
  - steelseries-exactmouse-tool
  - handbrake
  
  
mas_installed_apps:
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 498486288, name: "Quick Resizer" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 937984704, name: "Amphetamine" }


# configure_dock: true
# dockitems_remove:
#   - Launchpad
#   - TV
# dockitems_persist:
#   - name: "Sublime Text"
#     path: "/Applications/Sublime Text.app/"
#     pos: 5
