---
configure_dotfiles: true
configure_terminal: false
configure_osx: true
configure_dock: true

dotfiles_repo: https://github.com/Ruben-E//dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - asciidoctor
  - asciinema
  - autojump
  - awscli
  - git
  - glances
  - gradle
  - htop
  - httpie
  - jenv
  - jq
  - ncdu
  - nvm
  - podman
  - pure
  - rclone
  - restic
  - tldr
  - watch
  - wget
  - wrk
  - yarn
  - zsh
  - zsh-completions
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - pango
  - zlib
  - cairo

homebrew_cask_apps:
  - 1password
  - insomnia
  - aerial
  - cleanmymac
  - iterm2
  - contexts
  - alfred
  - jetbrains-toolbox
  - numi
  - appcleaner
  - discord
  - joplin
  - tunnelblick
  - postman
  - firefox
  - skype
  - slack
  - zoom
  - sourcetree
  - spotify
  - google-chrome
  - microsoft-office
  - microsoft-teams
  - handbrake
  - visual-studio-code
  - font-fira-code
  - steelseries-exactmouse-tool
  - logitech-camera-settings
  - intune-company-portal
  - citrix-workspace
  - chromium

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers

mas_installed_apps:
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 937984704, name: "Amphetamine" }

dockitems_remove:
  - Launchpad
  - TV
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - Podcasts
  - Keynote
  - Numbers
  - Pages
  - App Store
  - System Preferences
dockitems_persist: []