---
configure_dotfiles: true
configure_terminal: false
configure_osx: true
configure_dock: true

dotfiles_repo: https://github.com/Ruben-E/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - asciidoctor
  - asciinema
  - autojump
  - awscli
  - git
  - glances
  - gradle
  - htop
  - httpie
  - jenv
  - jq
  - ncdu
  - docker
  - pure
  - rclone
  - restic
  - tldr
  - watch
  - wget
  - wrk
  - yarn
  - zsh
  - pkg-config
  - maven
  - zplug

homebrew_cask_apps:
  - 1password
  - insomnia
  - aerial
  - cleanmymac
  - iterm2
  - contexts
  - alfred
  - jetbrains-toolbox
  - numi
  - appcleaner
  - discord
  - postman
  - firefox
  - skype
  - slack
  - zoom
  - spotify
  - google-chrome
  - microsoft-office
  - microsoft-teams
  - handbrake
  - visual-studio-code
  - font-fira-code
  - chromium
  - kap
  - brave-browser
  - steam
  - obsidian
  - font-jetbrains-mono

homebrew_taps:
  - homebrew/cask-fonts

mas_installed_apps:
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 937984704, name: "Amphetamine" }

dockitems_remove:
  - Launchpad
  - TV
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - Podcasts
  - Keynote
  - Numbers
  - Pages
  - App Store
  - System Settings
  - Freeform
dockitems_persist: []
